name: Build Grand Challenge Container

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Free up disk space on GitHub Runner
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Build Docker Image
      run: docker build -t pengwin-submission .

    - name: Save and Compress Docker Image 
      # We pipe the output directly into gzip to bypass file size limits
      run: docker save pengwin-submission | gzip > pengwin-submission.tar.gz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pengwin-container-archive
        path: pengwin-submission.tar.gz
        retention-days: 5
